### ISSUE TITLE
Wrong file encoding

### ISSUE THREAD

**Issue by jcubic** [schemedoc/surveys#11]
I was reading all the surveys and updating the Scheme interpreter and I've found this page:

https://doc.scheme.org/surveys/UnicodeLambda/

That display (what I think is supposed to be lambda character) as:

```scheme
((Îť () "ok")).
```

Because of wrong encoding. In these days since html5 was introduced UTF8 and Unicode are de facto standards for character encoding on the web.

**Comment by jcubic** [comment]
Another example https://doc.scheme.org/surveys/FixnumInfo/

**Comment by lassik** [comment]
Thanks. Now the HTML output says `<meta charset="UTF-8" />` which fixes the problem.

However, now there's the problem that our GitHub Flavored Markdown tables are broken. I'll add support to the Chicken `lowdown` egg (markdown parser).
